In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
##Preprocessing 
##Drop irrelevant columns
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
##Encoding categorical varuables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [12]:
#One-Hot encoding Geography
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [13]:
#Combining one-hot encoded columns with original data
data=pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [14]:
#Split data to features and target
X= data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [15]:
##Splitting data to training and test data
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
##Scaling the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [36]:
##saving encoders and scalers

with open('one_hot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('reg_scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [37]:
##ANN Regression problem statement
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [38]:
##Build ANN model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1], )), ##hl1 connected with input layer
    Dense(32, activation='relu'), ##hl2
    Dense(1) ##output
])

##compiling the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

/Users/sandeshsaidapur/ML Learning projects/ANNClassification/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
##Setting up tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

##Setting up Early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [40]:
##Training the model
history=model.fit(
    X_train, y_train, 
    validation_data=(X_test, y_test), 
    epochs=100, 
    callbacks=[early_stopping_callback, tensorflow_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 793us/step - loss: 100375.5234 - mae: 100375.5234 - val_loss: 98505.2031 - val_mae: 98505.2031
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - loss: 99580.4297 - mae: 99580.4297 - val_loss: 96889.1094 - val_mae: 96889.1094
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - loss: 96722.3672 - mae: 96722.3672 - val_loss: 92645.1797 - val_mae: 92645.1797
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - loss: 91011.6484 - mae: 91011.6484 - val_loss: 85528.5312 - val_mae: 85528.5312
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - loss: 82716.6641 - mae: 82716.6641 - val_loss: 76488.6719 - val_mae: 76488.6719
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - loss: 73173.1016 - mae: 73173.1016 - val_loss: 67286.6953 - val_mae: 67286.6953
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - loss: 64209.0703 - mae: 64209.0703 - val_loss: 59544.6016 - val_mae: 59544.6016
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - loss: 57405.6211 - mae: 57405.6211 - val_loss: 54504.8203 - val_mae: 54504.8203
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - loss: 53373.9414 - mae: 53373.9414 - val_loss: 51922.5391 - val_mae: 51922.5391
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - loss: 51377.4023 - mae: 51377.4023 - val_loss: 50940.3984 - val_mae: 50940.3984
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - loss: 50560.3750 - mae: 50560.3750 - val_loss: 50664.6211 - val_mae: 50664.6211
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 50276.8438 - mae: 50276.8438 - val_loss: 50580.8008 - val_mae: 50580.8008
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 50157.5742 - mae: 50157.5742 - val_loss: 50535.3047 - val_mae: 50535.3047
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 50083.0234 - mae: 50083.0234 - val_loss: 50501.6797 - val_mae: 50501.6797
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - loss: 50029.7734 - mae: 50029.7734 - val_loss: 50483.2031 - val_mae: 50483.2031
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - loss: 49982.9062 - mae: 49982.9062 - val_loss: 50458.1719 - val_mae: 50458.1719
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - loss: 49943.8789 - mae: 49943.8789 - val_loss: 50435.3164 - val_mae: 50435.3164
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 49909.9883 - mae: 49909.9883 - val_loss: 50414.8203 - val_mae: 50414.8203
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - loss: 49880.7383 - mae: 49880.7383 - val_loss: 50396.7656 - val_mae: 50396.7656
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - loss: 49852.8555 - mae: 49852.8555 - val_loss: 50387.7148 - val_mae: 50387.7148
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - loss: 49828.2305 - mae: 49828.2305 - val_loss: 50377.2227 - val_mae: 50377.2227
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 49805.5000 - mae: 49805.5000 - val_loss: 50368.7812 - val_mae: 50368.7812
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 49786.5039 - mae: 49786.5039 - val_loss: 50352.9102 - val_mae: 50352.9102
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - loss: 49767.4766 - mae: 49767.4766 - val_loss: 50353.4688 - val_mae: 50353.4688
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 49749.3711 - mae: 49749.3711 - val_loss: 50343.5664 - val_mae: 50343.5664
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - loss: 49731.9023 - mae: 49731.9023 - val_loss: 50338.2734 - val_mae: 50338.2734
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - loss: 49711.4648 - mae: 49711.4648 - val_loss: 50332.8945 - val_mae: 50332.8945
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 49702.2383 - mae: 49702.2383 - val_loss: 50329.7617 - val_mae: 50329.7617
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 49685.0352 - mae: 49685.0352 - val_loss: 50326.5312 - val_mae: 50326.5312
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - loss: 49671.0000 - mae: 49671.0000 - val_loss: 50323.9883 - val_mae: 50323.9883
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - loss: 49659.5938 - mae: 49659.5938 - val_loss: 50324.3359 - val_mae: 50324.3359
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - loss: 49646.0938 - mae: 49646.0938 - val_loss: 50322.9375 - val_mae: 50322.9375
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - loss: 49633.3516 - mae: 49633.3516 - val_loss: 50316.4023 - val_mae: 50316.4023
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - loss: 49622.0508 - mae: 49622.0508 - val_loss: 50318.5195 - val_mae: 50318.5195
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - loss: 49613.2109 - mae: 49613.2109 - val_loss: 50318.9766 - val_mae: 50318.9766
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - loss: 49601.5859 - mae: 49601.5859 - val_loss: 50318.2539 - val_mae: 50318.2539
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - loss: 49593.9062 - mae: 49593.9062 - val_loss: 50315.1602 - val_mae: 50315.1602
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - loss: 49583.3047 - mae: 49583.3047 - val_loss: 50317.8594 - val_mae: 50317.8594
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - loss: 49574.5859 - mae: 49574.5859 - val_loss: 50318.3398 - val_mae: 50318.3398
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 49562.8594 - mae: 49562.8594 - val_loss: 50321.3047 - val_mae: 50321.3047
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - loss: 49556.1016 - mae: 49556.1016 - val_loss: 50316.6133 - val_mae: 50316.6133
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - loss: 49545.4727 - mae: 49545.4727 - val_loss: 50340.5859 - val_mae: 50340.5859
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - loss: 49539.4531 - mae: 49539.4531 - val_loss: 50320.3086 - val_mae: 50320.3086
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - loss: 49531.9062 - mae: 49531.9062 - val_loss: 50317.7695 - val_mae: 50317.7695
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - loss: 49523.8516 - mae: 49523.8516 - val_loss: 50316.8398 - val_mae: 50316.8398
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - loss: 49516.1406 - mae: 49516.1406 - val_loss: 50317.8672 - val_mae: 50317.8672
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - loss: 49512.1055 - mae: 49512.1055 - val_loss: 50322.9883 - val_mae: 50322.9883

In [41]:
##Loading Tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [42]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6009 (pid 67345), started 0:28:46 ago. (Use '!kill 67345' to kill it.)

In [43]:
##Evaluating on test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 50315.1602 - mae: 50315.1602
Test MAE: 50315.16015625

In [44]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [46]:
print(scaler.feature_names_in_)

['CreditScore' 'Gender' 'Age' 'Tenure' 'Balance' 'NumOfProducts'
 'HasCrCard' 'IsActiveMember' 'Exited' 'Geography_France'
 'Geography_Germany' 'Geography_Spain']